version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  default: standard
  disable:
    - unused
    - errcheck

  settings:
    staticcheck:
      checks:
        - "all"
        - "-QF*"
        - "-SA5011"
        - "-ST1003"
        - "-SA4006"
        - "-SA4010"

  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
    paths:
      - vendor
      - testdata
      - examples
      - bin
      - .worktrees
    rules:
      - path: _test\.go
        linters:
          - gosec
          - ineffassign

formatters:
  enable:
    - gofmt
    - goimports
